### ISSUE TITLE
What's the extension?

### ISSUE THREAD

**Issue by GabrielCrocker7** [julesfrn/bomb-party-bot#1]
Not really an issue, I just don't know how you get it. If it's a chrome extension then how do I get it?

**Comment by julesfrn** [comment]
hello, sorry for the delay of my response you need to download or clone this repository and tell chrome to use it as an extension. When you go to chrome, go to the adress chrome://extensions and enable the dev mode, then you can load the unpacked extension with the corresponding button

**Comment by julesfrn** [comment]
I'm not sure the extension still works though
